### ISSUE TITLE
【提案】ステージなどイベントの時間通知機能

### ISSUE THREAD

**Issue by chigakucat** [chigakucat/uchikoshi42nd#15]
提案内容: オンサイト文化祭を対象とした機能。ステージなどの時間が近づいてきたときに、「この後○○:○○からステージで△△を行います」といったプッシュ通知をする。

メリット:
オンサイト文化祭でこのアプリを使う意味が出る。
ステージを見逃すといったことを防げる。

デメリット:
オンサイト文化祭に参加しない人にとってはいらない機能（あらかじめ一般に告知するか、アプリ内で通知設定をできるようにすればok?）
浅野生が校内でスマホを使えないので、そこの改善が必要

**Comment by supermouse732e73** [comment]
私が作業します
