### ISSUE TITLE
【提案】投票の類をできるようにする

### ISSUE THREAD

**Issue by chigakucat** [chigakucat/uchikoshi42nd#18]
友人からの提案

問題: ミスターミスAsano The Bestなどを投票するためには投票所へ行かなければならない。
提案内容: アプリから投票できるようにできないか？

メリット・デメリット
メリット:
手軽さが増すので多少投票数が増えるかも？
デメリット:
組織票など不正投票は阻止できない。←google フォームでasano.ed.jpからの投票に限定することはできるが、それだと一般来場者には利点がない。

**Comment by chigakucat** [comment]
おそらく生徒が校内でスマホ使うのは無理

**Comment by supermouse732e73** [comment]
私が作業します

**Comment by chigakucat** [comment]
コメント取り消しのため削除

**Comment by chigakucat** [comment]
機能追加しません。
